name: Windows - LiteManager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Download & Run Setup
        shell: powershell
        run: |
          iwr -Uri "https://raw.githubusercontent.com/header123z/vps/refs/heads/main/download.bat" -OutFile "download.bat"
          cmd /c download.bat

      - name: Show LiteManager Info
        run: |
          if exist show.bat (
            cmd /c show.bat
          ) else (
            echo No show.bat found yet.
          )

      - name: Keep Alive
        run: |
          echo :loop > loop.bat
          echo timeout /t 3600 >> loop.bat
          echo goto loop >> loop.bat
          cmd /c loop.bat
